// GENERATED from js/i18n.js by tools/gen-ios-strings.js. Do not edit by hand.

enum L10nTable {
    static let ja: [String: String] = [
        "back": "もどる",
        "canvas.label": "ゲーム画面：タップまたはスペースキーでリングを切り替え",
        "hint.start": "タップで\n内⇄外",
        "hud.combo": "{n} combo",
        "menu.daily": "📅 今日のチャレンジ",
        "menu.dailyBonus": "デイリーボーナス 🪙+{bonus}（{streak}日連続）",
        "menu.haptics": "振動切替",
        "menu.lang": "言語を切り替え（English）",
        "menu.missions": "ミッション",
        "menu.new": "NEW",
        "menu.play": "タップでスタート",
        "menu.skins": "スキン",
        "menu.sound": "サウンド切替",
        "menu.tagline": "タップで内側⇄外側。<wbr>トゲをよけて<wbr>ジェムを集めろ。",
        "menu.taglineApp": "タップで内側⇄外側。\nトゲをよけてジェムを集めろ。",
        "meta.description": "タップだけで遊べる中毒性ワンタップゲーム。内側と外側のリングを切り替えてトゲをよけ、ジェムを集めてフィーバーを狙え。",
        "mission.bestCombo": "コンボ{n}達成",
        "mission.feverCount": "ワンプレイでフィーバー{n}回",
        "mission.gems": "ワンプレイでジェム{n}個",
        "mission.nearMisses": "ワンプレイでニアミス{n}回",
        "mission.plays": "{n}回プレイ",
        "mission.score": "ワンプレイで{n}点",
        "missions.lifetime": "通算 {plays} プレイ ・ ジェム {gems} 個 ・ Lv {level}",
        "missions.title": "ミッション",
        "over.bestCombo": "最大コンボ",
        "over.canUnlock": "🔓 スキン「{name}」を解放できます！",
        "over.daily": "📅 今日のチャレンジ",
        "over.gems": "ジェム",
        "over.levelUp": "レベルアップ!",
        "over.menu": "メニュー",
        "over.nearMisses": "ニアミス",
        "over.nextUnlock": "次のスキン「{name}」まで 🪙{n}",
        "over.retry": "もう一回 ↻",
        "over.share": "スコアを共有",
        "over.smashed": "粉砕",
        "over.tease.close": "おしい！ あと{n}点でベスト更新！",
        "over.tease.far": "ベストまで あと{n}点",
        "over.tease.first": "初記録！ 次はこれを超えよう",
        "over.tease.newBest": "記録更新！ +{n}",
        "over.tease.tied": "ベストに並んだ！ あと1点で更新！",
        "over.tease.zero": "トゲをよけると1点！ タップで内⇄外を切替",
        "over.try": "（{n}回目）",
        "pause.hint": "Esc / P でも一時停止・再開できます",
        "pause.resume": "タップで再開",
        "pause.title": "一時停止",
        "share.copied": "コピーしました！",
        "share.daily": "ORBIT SWITCH 今日のチャレンジ（{day}）で {score}点！ 同じステージで勝負しよう #ORBITSWITCH",
        "share.failed": "コピーできませんでした",
        "share.normal": "ORBIT SWITCH で {score}点！（ベスト {best}）タップだけの中毒ゲーム #ORBITSWITCH",
        "shop.buy": "購入",
        "shop.equipped": "使用中",
        "shop.notEnough": "コインが足りません（あと 🪙{n}）— プレイして集めよう！",
        "shop.owned": "所持",
        "shop.title": "スキン",
        "skin.ghost": "ゴースト",
        "skin.lime": "ライム",
        "skin.neon": "ネオン",
        "skin.rainbow": "レインボー",
        "skin.sakura": "サクラ",
        "skin.sun": "サン",
        "skin.void": "ヴォイド",
    ]
    static let en: [String: String] = [
        "back": "Back",
        "canvas.label": "Game screen: tap or press Space to switch rings",
        "hint.start": "TAP TO\nSWITCH",
        "hud.combo": "{n} combo",
        "menu.daily": "📅 Daily Challenge",
        "menu.dailyBonus": "Daily bonus 🪙+{bonus} · {streak}-day streak",
        "menu.haptics": "Toggle vibration",
        "menu.lang": "Switch language (日本語)",
        "menu.missions": "Missions",
        "menu.new": "NEW",
        "menu.play": "TAP TO PLAY",
        "menu.skins": "Skins",
        "menu.sound": "Toggle sound",
        "menu.tagline": "Tap to switch rings.<wbr> Dodge spikes,<wbr> grab gems.",
        "menu.taglineApp": "Tap to switch rings.\nDodge spikes, grab gems.",
        "meta.description": "A one-tap game you can’t put down. Switch between the inner and outer ring, dodge spikes, grab gems and chase the fever.",
        "mission.bestCombo": "Reach a {n} combo",
        "mission.feverCount": "Trigger fever {n}× in one run",
        "mission.gems": "Collect {n} gems in one run",
        "mission.nearMisses": "{n} near misses in one run",
        "mission.plays": "Play {n} times",
        "mission.score": "Score {n} in one run",
        "missions.lifetime": "{plays} plays · {gems} gems · Lv {level}",
        "missions.title": "Missions",
        "over.bestCombo": "Best combo",
        "over.canUnlock": "🔓 You can unlock the {name} skin!",
        "over.daily": "📅 Daily Challenge",
        "over.gems": "Gems",
        "over.levelUp": "Level up!",
        "over.menu": "Menu",
        "over.nearMisses": "Near misses",
        "over.nextUnlock": "🪙{n} to the {name} skin",
        "over.retry": "Retry ↻",
        "over.share": "Share score",
        "over.smashed": "Smashed",
        "over.tease.close": "So close! {n} more to beat your best!",
        "over.tease.far": "{n} points to your best",
        "over.tease.first": "First score! Now beat it",
        "over.tease.newBest": "New record! +{n}",
        "over.tease.tied": "Tied your best! 1 more point to beat it!",
        "over.tease.zero": "Dodge a spike for 1 point! Tap to switch rings",
        "over.try": " (try {n})",
        "pause.hint": "Esc / P also pauses and resumes",
        "pause.resume": "Tap to resume",
        "pause.title": "Paused",
        "share.copied": "Copied!",
        "share.daily": "I scored {score} in today’s ORBIT SWITCH Daily Challenge ({day})! Same stage for everyone — beat me. #ORBITSWITCH",
        "share.failed": "Couldn’t copy",
        "share.normal": "I scored {score} in ORBIT SWITCH! (best {best}) One tap, can’t stop. #ORBITSWITCH",
        "shop.buy": "Buy",
        "shop.equipped": "Equipped",
        "shop.notEnough": "Not enough coins (🪙{n} more) — play to earn more!",
        "shop.owned": "Owned",
        "shop.title": "Skins",
        "skin.ghost": "Ghost",
        "skin.lime": "Lime",
        "skin.neon": "Neon",
        "skin.rainbow": "Rainbow",
        "skin.sakura": "Sakura",
        "skin.sun": "Sun",
        "skin.void": "Void",
    ]
}
